---
title: "STA302 Tut1"
author: "Alexander Guarasci"
format: html
---
```{r}
#### Preamble ####
# Purpose: Read in data from the Canadian Election and make
# a graph of the number of seats each party won.
# Author: Alexander Guarasci
# Email: alexander.guarasci@mail.utoronto.ca
# Date: 8 January 2023
# Prerequisites: Know where to get Canadian elections data.

library(tidyverse)
library(janitor)
```

```{r}
simulated_data <-
  tibble(
    # Use 1 through to 151 to represent each division
    "Division" = 1:338,
    # Randomly pick an option, with replacement, 151 times
    "Party" = sample(
      x = c("Liberal", "Conservative", "Bloc Québécois", "New Democratic", "Green", "Other"),
      size = 338,
      replace = TRUE
    )
  )

simulated_data
```

```{r}
#### Basic cleaning ####
raw_elections_data <-
  read_csv(
    file = "table_tableau11.csv",
    show_col_types = FALSE
  )
# Make the names easier to type
cleaned_elections_data <-
  clean_names(raw_elections_data)

# Have a look at the first six rows
head(cleaned_elections_data)
```

```{r}
cleaned_elections_data <-
  cleaned_elections_data |>
  select(
    electoral_district_name_nom_de_circonscription,
    elected_candidate_candidat_elu
  )

head(cleaned_elections_data)
```

```{r}
names(cleaned_elections_data)
cleaned_elections_data <-
  cleaned_elections_data |>
  rename(
    district = electoral_district_name_nom_de_circonscription,
    elected_candidate = elected_candidate_candidat_elu
  )

head(cleaned_elections_data)
```

```{r}
cleaned_elections_data <-
  cleaned_elections_data |>
  separate(
    col = elected_candidate,
    into = c("Other", "party"),
    sep = "/"
  ) |>
  select(-Other)
head(cleaned_elections_data)
```

```{r}
cleaned_elections_data <-
  cleaned_elections_data |>
  mutate(
    party =
      case_match(
        party,
        "Libéral" ~ "Liberal",
        "Conservateur" ~ "Conservative",
        "NPD-Nouveau Parti démocratique" ~ "New Democratic",
        "Parti Vert" ~ "Green",
        "Bloc Québécois" ~ "Bloc Québécois",
      )
  )

head(cleaned_elections_data)
```


```{r}
write_csv(
  x = cleaned_elections_data,
  file = "cleaned_elections_data.csv"
  )
```

```{r}
cleaned_elections_data <-
  read_csv(
    file = "cleaned_elections_data.csv",
    show_col_types = FALSE
  )

cleaned_elections_data |>
  count(party)
```
```{r}
cleaned_elections_data |>
  ggplot(aes(x = party)) + # aes abbreviates "aesthetics" 
  geom_bar()

cleaned_elections_data |>
  ggplot(aes(x = party)) +
  geom_bar() +
  theme_minimal() + # Make the theme neater
  labs(x = "Party", y = "Number of seats") # Make labels more meaningful
```



